export {default as Header} from "./header/Header"
export {default as Footer} from "./footer/Footer"
export {default as Home} from "./home/Home"
export {default as About} from "./about/About"
export {default as Nav} from "./nav/Nav"
